const DrugsData = ["Methyl-2-(naphthalen-2-yl)-2-acetate",
"1-Androstenediol",
"1-Androstenedione", 
"1-Androsterone", 
"1-Epiandrosterone", 
"1-Testosterone", 
"2-Androstenol", 
"2-Androstenone", 
"3-Androstenol", 
"3-Androstenone", 
"3-Methylhexan-2-amine", 
"4-Androstene-3,6,17 trione",  
"4-Androstenediol",  
"4-Fluoromethylphenidate",  
"4-Hydroxytestosterone",  
"4-Methylhexan-2-amine",  
"4-Methylpentan-2-amine",  
"5-Androstenedione",  
"5-Methylhexan-2-amine",  
"7-Keto-DHEA",  
"7α-hydroxy-DHEA",  
"7β-hydroxy-DHEA",  
"19-Norandrostenediol",  
"19-Norandrostenedione",
"ACE-031",  
"Acebutolol",  
"Acetazolamide",  
"Activin A-neutralizing antibodies",  
"Activin receptor IIB competitors",  
"Adrafinil",  
"Adderall",
"Adrenaline",  
"AICAR",  
"Albumin",  
"Alexamorelin",  
"Alprenolol",  
"Amfepramone",  
"Amfetamine",  
"Amfetaminil",  
"Amiloride",  
"Aminoglutethimide",  
"Amiphenazole",  
"AMP-activated protein kinase",  
"Anamorelin",  
"Anastrozole",  
"Andarine",  
"Androsta-1,4,6-triene-3,17-dione",  
"Androsta-3,5-diene-7,17-dione",  
"Androstanolone",  
"Androstatrienedione",  
"Androstenediol",  
"Androstenedione",  
"Anti-activin receptor IIB antibodies",  
"AOD-9604",  
"Arformoterol",  
"Arimistane",  
"Asialo EPO",  
"Atenolol",  
"Bazedoxifene",  
"Beclometasone",  
"Bendroflumethiazide",  
"Benfluorex",  
"Benzfetamine",  
"Benzylpiperazine",  
"Betamethasone",  
"Betaxolol",  
"Bimagrumab",  
"Bisoprolol",  
"Bolasterone",  
"Boldenone",  
"Boldione",  
"BPC- 7", 
"Brimonidine",  
"Brinzolamide",  
"Bromantan",  
"Budesonide",  
"Bumetanide",  
"Bunolol",  
"Buprenorphine",  
"Buserelin",  
"Calusterone",  
"Cannabidiol",  
"Cannabis",  
"Canrenone",  
"Carbamylated EPO",  
"Carteolol",  
"Carvedilol",  
"Cathine",  ,  
"Cathinone",  
"Celiprolol",  
"Chlorothiazide",  
"Chlortalidone",  
"Chorionic Gonadotrophin",  
"Ciclesonide",  
"CJC-1293",  
"CJC-1295",  
"Clenbuterol",  
"Clobenzorex",  
"Clomifene",  
"Clonazoline",  
"Clonidine",  
"Clostebol", 
"CNTO-530",  
"Cobalt",  
"Cocaine",  
"Corticorelin",  
"Corticotrophins",  
"Cortisone",  
"Cropropamide",  
"Crotetamide",  
"Cyclofenil",  
"Danazol",  
"Daprodustat",  
"Darbepoetins",  
"Deflazacort",  
"Dehydrochlormethyltestosterone",  
"Deslorelin",  
"Desmopressin",  
"Desoxymethyltestosterone",  
"Dexamethasone",  
"Dextran",  
"Dextromoramide",  
"Diamorphine",  
"Dimetamfetamine",  
"Dimethylamphetamine",  
"Domagrozumab",  
"Dorzolamide",  
"Drospirenone",  
"Drostanolone",  
"Efaproxiral" ,
"RSR13",  
"Enobosarm",  
"Ephedrine",  ,  
"Epiandrosterone",  
"Epi-dihydrotestosterone",  
"Epinephrine",  
"Epitestosterone",  
"EPO-based constructs",  
"EPO-Fc",  
"EPO-mimetic agents",  
"Erythropoietin receptor agonists",  
"Erythropoietins",
"EPO",  
"Esmolol",  
"Etacrynic acid",  
"Etamivan",  
"Ethylestrenol",  
"Ethylphenidate",  
"Etilamfetamine",  
"Etilefrine",  
"Examorelin",  
"Exemestane",  
"Famprofazone",  
"Felypressin",  
"Fenbutrazate",  
"Fencamfamin",  
"Fencamine",  
"Fenetylline",  
"Fenfluramine",  
"Fenoterol",  
"Fenoxazoline",  
"Fenproporex",  
"Fentanyl",   
"Flunisolide",  
"Fluocortolone",  
"Fluorenol",  
"Fluoxymesterone",  
"Fluticasone",  
"Follistatin",  
"Fonturacetam",  
"Formebolone",  
"Formestane",  
"Formoterol",  ,  
"Fulvestrant",  
"Furazabol",  
"Furfenorex",  
"Furosemide",  
"GATA inhibitors",  
"Gestrinone",  
"GHRPs",  
"Gonadorelin",  
"Goserelin",  
"Growth hormone",
"GW1516",  
"GW501516",  
"Hashish",  
"Hepatocyte growth factor",  
"Heptaminol",  
"Heroin",  
"Hexarelin",  
"Higenamine",  
"Hydrafinil",  
"Hydrochlorothiazide",  
"Hydrocortisone",  
"Hydromorphone",  
"Hydroxyamfetamine",  
"Hydroxyethyl starch",  
"Hypoxia-inducible factor activating agents",  
"Imidazoline",  
"Indacaterol",  
"Indanazoline",  
"Indapamide",  
"Infusions",  
"Innate repair receptor agonists",  
"Insulin-like growth factor-1",  
"Insulin-mimetics",  
"Insulins",  
"Intravenous infusions",  
"IOX2",  
"Ipamorelin",  
"Isometheptene",  
"K-11706",  
"Labetalol",  
"Landogrozumab",  
"Lenomorelin",  
"Letrozole",  
"Leuprorelin",  
"Levmetamfetamine",  
"Levosalbutamol",  
"LGD-4033",  
"Ligandrol",  
"Lisdexamfetamine",  
"Lonapegsomatropin",  
"Luspatercept",  
"Luteinizing hormone",  
"Macimorelin",  
"Mannitol",  
"Marijuana",    
"Meclofenoxate",  
"Mefenorex",  
"Meldonium",  
"Mephedrone",  
"Mephentermine",  
"Mesocarb",  
"Mestanolone",  
"Mesterolone",  
"Metamfetamine",  
"Metandienone",  
"Metenolone",  
"Methadone",  
"Methandriol",  
"Methasterone",  
"Methedrone",  
"Methoxy polyethylene glycol-epoetin beta",  
"Methyl-1-testosterone",  
"Methylclostebol",  
"Methyldienolone",  
"Methylenedioxymethamphetamine",  
"Methylephedrine",  ,  
"Methylnaphtidate",  
"Methylnortestosterone",  
"Methylphenidate",  
"Methylprednisolone",  
"Methylsynephrine",  
"Methyltestosterone",  
"Metipranolol",  
"Metolazone",  
"Metoprolol",  
"Metribolone",  
"Mibolerone",  
"Modafinil",  
"Molidustat",  
"Mometasone",  
"Morphine",  
"Myostatin inhibitors",  
"Myostatin propeptide",  
"Myostatin-binding proteins",  
"Myostatin-neutralizing antibodies",
"Nadolol",  
"Nafarelin",  
"Nandrolone",  
"Naphazoline",  
"Nebivolol",  
"Nicomorphine",  
"Nikethamide",  
"Norboletone",  
"Norclostebol",  
"Norethandrolone",  
"Norfenefrine",  
"Norfenfluramine",  
"Nucleic acids",  
"Nucleic acid analogues",
"Octodrine",  
"Octopamine",  
"Olodaterol",  
"Osilodrostat",  
"Ospemifene",  
"Ostarine",  
"Oxabolone",  
"Oxandrolone",  
"Oxilofrine",  
"Oxprenolol",  
"Oxycodone",  
"Oxymesterone",  
"Oxymetazoline",  
"Oxymetholone",  
"Oxymorphone",  
"Pamabrom",  
"Parahydroxyamphetamine",  
"Peginesatide",  
"Pemoline",  
"Pentazocine",  
"Pentetrazol",  
"Perfluorochemicals",  
"Peroxisome proliferator activated receptor delta agonists",  
"Pethidine",  
"Phendimetrazine",  
"Phenethylamine",  
"Phenmetrazine",  
"Phenpromethamine",  
"Phentermine",  
"Pindolol",  
"Plasma expanders",  
"Platelet-derived growth factor",  
"p-methylamfetamine",  
"Pralmorelin",  
"Prasterone",  
"Prednisolone",  
"Prednisone",  
"Prenylamine",  
"Probenecid",  
"Procaterol",  
"Prolintane",  
"Propranolol",  
"Propylhexedrine",  
"Prostanozol",  
"Proteases",  
"Pseudoephedrine",
"Quinbolone",  
"RAD140",  
"Raloxifene",  
"Reproterol",  
"Roxadustat",  
"Salbutamol",  ,  
"Salmeterol",  
"Selective androgen receptor modulators",
"Selegiline",
"Sermorelin", 
"Sibutramine",
"Somapacitan",
"Somatrogon",
"Sotalol", 
"Sotatercept", 
"Spironolactone", 
"SR9009", 
"Stamulumab", 
"Stanozolol", 
"Stenbolone", 
"Strychnine", 
"Tabimorelin", 
"Tamoxifen", 
"Tampering",
"TB-500",
"Tenamfetamine",
"Terbutaline",
"Tesamorelin",
"Testolactone",
"Testosterone",
"Tetrahydrocannabinols",
"Tetrahydrogestrinone",
"Thiazides",
"Thymosin-β4",
"Tibolone",
"Timolol",
"Tolvaptan",
"Toremifene",
"Transforming growth factor beta (TGF-β) signalling inhibitors",
"Trenbolone",
"Tretoquinol",
"Triamcinolone acetonide",
"Triamterene",
"Trimetazidine",
"Trimetoquinol",
"Triptorelin",
"Tuaminoheptane",
"Tulobuterol",
"Vadadustat",
"Vaptans",
"Vascular endothelial growth factor",
"Vilanterol",
"Xenon",
"Xylometazoline",
"Zeranol",
"Zilpaterol",
"Mucovib",
"Nimesulide"];

const medicineAlternative = {"adderall":["Noocube", "Vyvamind", "Mind Lab Pro"], "mucovib":["Benedryl", "Dabur Honitus Syrup", "Patanjali Divya SWASARI PRAVAHI"], 
                             "nimesulide":["Paracetamol", "Termadol", "Codeine"]};
const medicineSideEffects = {"adderall":["Nervousness", "depression", "Hallucination"], "mucovib":["Drowsinees", "Uncontrollable Shaking of body", "Headache"],
                             "nimesulide":["Gastrointestinal Upset", "Hypersensitivity reactions", "Abdominal discomfort"]};

const lower=[], medAlt={}, MedSa = {};
DrugsData.forEach(element => {
    lower.push(element.toLowerCase());
  });
 
module.exports = {
    getRArray: function() {
      return lower;
    },

    getMa: function(){
      return medicineAlternative;
    },

    getMsa: function(){
      return medicineSideEffects;
    }

  };